### ISSUE TITLE
Failed to activate the arduino-atom package

### ISSUE THREAD

**Issue by taalabash** [ido-ran/arduino-atom#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [arduino-atom](https://github.com/ido-ran/arduino-atom) package 0.1.0

### Stack Trace

Failed to activate the arduino-atom package

```
At Cannot find module 'etch'

Error: Cannot find module 'etch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/arduino-atom-0.1.0/lib/arduino-dev-pane.js:13:13)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/arduino-atom-0.1.0/lib/arduino.js:11:23)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:246:26)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:13.9.0 find-and-replace:show (input.hidden-input)
  6x -4:58.2.0 core:backspace (input.hidden-input)
     -4:56.3.0 editor:consolidate-selections (input.hidden-input)
     -4:56.3.0 core:cancel (input.hidden-input)
     -4:50.2.0 core:save (input.hidden-input)
     -4:26.9.0 find-and-replace:show (input.hidden-input)
     -4:23.4.0 core:backspace (input.hidden-input)
     -4:21 project-find:show (input.hidden-input)
     -4:20.5.0 core:confirm (input.hidden-input)
     -3:41.9.0 find-and-replace:show (input.hidden-input)
     -3:33.6.0 core:confirm (input.hidden-input)
     -3:27.7.0 project-find:show (input.hidden-input)
  2x -3:27.1.0 core:confirm (input.hidden-input)
     -1:42.3.0 tree-view:remove (span.name.icon.icon-file-text)
 24x -0:42 core:backspace (input.hidden-input)
     -0:16.3.0 arduino:toggle (input.hidden-input)
```

### Non-Core Packages

```
arduino-atom 0.1.0 
```

**Comment by ido-ran** [comment]
Hi,
Thank you for filing this issue. I've not updated this plugin for a long time and it looks like a dependency was changed.

I can try to update it but I can't commit to a specific time frame.

**Comment by jhoanmartinezz** [comment]
issues
1. stay downlad forever, so i clone it to my package at atom folder
2. keybindings Failed to activate the arduino-atom package, so change all the .json files to .cson files
3. finally y press the keybindings  but nothing happen, i really like this tool
greetings yall
