### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setText' of undefined

### ISSUE THREAD

**Issue by alekseychikin** [ido-ran/arduino-atom#4]
[Enter steps to reproduce:]

1. Toggle Arduino panel
2. Click Compile or Upload

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [arduino-atom](https://github.com/ido-ran/arduino-atom) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setText' of undefined

```
At /Users/makingoff/.atom/packages/arduino-atom/lib/arduino-dev-pane.js:144

TypeError: Cannot read property 'setText' of undefined
    at ArduinoDevPane.clearOutput (/packages/arduino-atom/lib/arduino-dev-pane.js:144:32)
    at ArduinoPlugin.compile (/packages/arduino-atom/lib/arduino.js:95:18)
    at ArduinoPlugin.handleCompile (/packages/arduino-atom/lib/arduino.js:60:10)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ArduinoDevPane.handleCompileButton (/packages/arduino-atom/lib/arduino-dev-pane.js:75:18)
```

### Commands

```
     -0:19.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:12.5.0 command-palette:toggle (input.hidden-input)
     -0:07.7.0 core:confirm (input.hidden-input)
     -0:07.4.0 arduino:toggle (input.hidden-input)
     -0:04.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
arduino-atom 0.1.0 
atom-beautify 0.30.5 
autocomplete-clang 0.11.3 
autocomplete-js 0.1.0 
busy-signal 1.4.3 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.11 
gulp-runner 0.2.3 
intentions 1.1.5 
language-arduino 0.4.3 
language-gutt 0.0.6 
language-ini 1.19.0 
language-postcss 1.3.1 
language-scala 1.1.9 
language-twig 1.6.3 
linter 2.2.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-stylelint 4.0.1 
linter-ui-default 1.6.7 
mark 1.3.3 
php-debug 0.2.5 
pigments 0.40.2 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
webdriverio-mobile-snippets 0.1.0 
webdriverio-snippets 0.3.2 
```

**Comment by janoist1** [comment]
Same here. Has it been resolved?

**Comment by ido-ran** [comment]
Hi,
Sorry about the delay.
I don’t have time to handle this problem.

Ido
