### ISSUE TITLE
Uncaught Error: Cannot find module 'etch'

### ISSUE THREAD

**Issue by AlexMshc** [ido-ran/arduino-atom#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [arduino-atom](https://github.com/ido-ran/arduino-atom) package 0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'etch'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module 'etch'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146745)
    at /packages/arduino-atom-master/lib/arduino-dev-pane.js:13:13)
    at /packages/arduino-atom-master/lib/arduino-dev-pane.js:203:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146745)
    at /packages/arduino-atom-master/lib/arduino.js:11:23)
    at /packages/arduino-atom-master/lib/arduino.js:207:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:714332)
    at Package.requireMainModule (<embedded>:11:3417381)
    at Package.activateConfig (<embedded>:11:3406669)
    at PackageManager.packageHasSettings (<embedded>:11:930790)
    at PackageCard.hasSettings (<embedded>:14:2616178)
    at PackageCard.updateSettingsState (<embedded>:14:2606458)
    at PackageCard.updateInterfaceState (<embedded>:14:2606281)
    at new PackageCard (<embedded>:14:2597878)
    at PackageDetailView.completeInitialization (<embedded>:14:823257)
    at PackageDetailView.loadPackage (<embedded>:14:823824)
    at new PackageDetailView (<embedded>:14:820410)
    at SettingsView.getOrCreatePanel (<embedded>:11:952869)
    at SettingsView.showPanel (<embedded>:11:953590)
    at SettingsView.showDeferredPanel (<embedded>:11:953514)
    at SettingsView.initializePanels (<embedded>:11:950971)
    at <embedded>:11:948147
    at process._tickCallback (internal/process/next_tick.js:61:11)

```

### Commands

```
```

### Non-Core Packages

```
arduino-atom 0.1.0 
atom-beautify 0.33.4 
file-icons 2.1.35 
platformio-ide-terminal 2.9.4 
simplified-russian-menu 1.3.0 
teletype 0.13.4 
```

**Comment by ido-ran** [comment]
Hi, sorry but I'm not maintaining this plugin anymore 😞
