### ISSUE TITLE
Installing “arduino-atom@0.1.0” failed.

### ISSUE THREAD

**Issue by georgebutter** [ido-ran/arduino-atom#8]
macOS Catalina 10.15.5

Stack trace
```
> serialport@4.0.7 install /private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport
> node-pre-gyp install --fallback-to-build

Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release' (1)

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
node-pre-gyp verb cli   '/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.20.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v5.0-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v5.0-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v5.0-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@5.0.13 (electron-v5.0 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v5.0-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v5.0-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@5.0.13 (electron-v5.0 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release"
gyp ERR! cwd /private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release"
gyp ERR! cwd /private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/node_modules/arduino-atom/node_modules/serialport
node-pre-gyp ERR! node -v v10.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 

npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/dv/586s8q555_qfgl9zw56531r00000gn/T/apm-install-dir-2020626-4505-m3k5x9.k2mbh/package.json'
npm WARN apm-install-dir-2020626-4505-m3k5x9.k2mbh No description
npm WARN apm-install-dir-2020626-4505-m3k5x9.k2mbh No repository field.
npm WARN apm-install-dir-2020626-4505-m3k5x9.k2mbh No README data
npm WARN apm-install-dir-2020626-4505-m3k5x9.k2mbh No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/georgebutter/.atom/.apm/_logs/2020-07-26T10_34_34_917Z-debug.log
```

**Comment by NikonP** [comment]
Same issue on Arch Linux

**Comment by ido-ran** [comment]
Sorry, I don't have time to maintain this project.

**Comment by georgebutter** [comment]
@ido-ran fair enough mate.
